config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :products
  resources :purchases, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private

  def authenticate_user!
    unless user_signed_in?
      flash[:alert] = "Debe ingresar como usuario para poder acceder a esta sección."
      redirect_to new_session_path
    end
  end

  def user_signed_in?
    session[:user_id].present?
  end

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end
  helper_method :user_signed_in?
  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      flash[:notice] = "Hemos publicado tu aviso de #{@product.name}!"
      redirect_to root_path
    else
      flash[:alert] = "Error: " + @product.errors.full_messages.join(', ')
      redirect_to new_product_path
    end

  end

  private

  def product_params
    params.require(:product).permit(:name, :image, :price, :description)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    Purchase.create(user_id: current_user.id, product_id: @product.id)
    flash[:notice] = "Has comprado #{@product.name}"
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.where(email: params[:user][:email])
    if @user.any? && @user.first.authenticate(params[:user][:password])
      session[:user_id] = @user.first.id
      flash[:notice] = "Ingreso exitoso. Hola #{@user.first.name}!"
    else
      flash[:alert] = "Error: Los datos ingresados no corresponden a ningún usuario."
      redirect_to new_session_path and return
    end
    redirect_to root_path
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "Sesión finalizada"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Usuario creado exitosamente"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:notice] = @user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_if(controller, action)
    'active' if current_page?(controller: controller, action: action)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def is_purchased?(product)
    Purchase.where(product_id: product.id).any?
  end

  def product_owner(product)
    User.find(product.user_id)
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
<div class="alert alert-info">
  <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-danger">
  <%= flash[:alert] %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">PseudoYapo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Registro
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <a class="dropdown-item" href="<%= user_path(current_user) %>">Ver perfil</a>
            <div class="dropdown-divider"></div>
            <%= link_to 'Cerrar sesión', session_path(id: current_user.id), method: :delete, class: 'dropdown-item' %>
          <% else %>
            <a class="dropdown-item" href="<%= new_session_path %>">Ingresar</a>
            <a class="dropdown-item" href="<%= new_user_path %>">Registrarse</a>
          <% end %>
        </div>
      </li>
      <li class="nav-item <%= active_if('products', 'index') %>">
        <a class="nav-link" href="<%= root_path %>">Comprar</a>
      </li>
      <li class="nav-item <%= active_if('products', 'new') %>">
        <a class="nav-link" href="<%= new_product_path %>">Vender</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PseudoYapo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/new.html.erb
  <div class="new-user-form">
    <h2>Register new user</h2>
  <%= form_with model: @user do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div class="form-group">
    <%= form.submit class: 'btn btn-default' %>
  </div>
  <% end %>
  </div>
<script type="text/javascript">
  $('body').toggleClass('background-gradient');
</script>

app/views/products/_form.html.erb
<%= form_with model: @product do |f| %>
<div class="form-group">
  <div class="form-row">
    <div class="col-xs-12 col-sm-6 col-md-5 my-2">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Nombre del producto...' %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-5 my-2">
      <%= f.url_field :image, class: 'form-control', placeholder: 'URL de la imagen del producto...' %>
    </div>
    <div class="col-xs-12 col-sm-2 col-md-2 my-2">
      <%= f.number_field :price, class: 'form-control', placeholder: '$...' %>
    </div>
    <div class="col-xs-12 col-sm-10 col-md-12 my-2">
      <%= f.text_area :description, class: 'form-control', placeholder: 'Ingrese la descripción del producto...' %>
    </div>
    <div class="col-sm-12">
      <h1><%= f.submit 'Publicar aviso!', class: 'btn btn-primary w-100' %></h1>
    </div>
  </div>
</div>
<% end %>

app/views/products/index.html.erb
<div class="row">
  <% @products.each do |p| %>
    <% unless is_purchased?(p) %>
    <div class="card mx-auto my-2" style="width: 18rem;">
      <img class="card-img-top" src="<%= p.image %>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= p.name.capitalize %></h5>
        <h6 class="card-subtitle mb-2 text-muted">$<%= number_with_delimiter(p.price.to_i, delimiter: '.').to_s %>.-</h6>
        <p class="card-text"><%= p.description.truncate(100) %></p>
        <%= link_to 'Comprar', purchases_path(product_id: p.id), class: 'btn btn-primary', method: :post, data: {confirm: "Está seguro de que desea comprar #{p.name.capitalize}?"} %>
      </div>
      <div class="card-footer text-muted">
        <% if user_signed_in? %>
          <%= link_to "Publicado por: #{product_owner(p).name}", '#', data: {toggle: 'modal', target: '.modal'} %>
        <% else %>
          Publicado por: <%= product_owner(p).name %>
        <% end %>
      </div>
      <!-- MODAL START -->
      <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Perfil del usuario</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                  <div class="col-md-4">
                    <img src="https://cdn1.iconfinder.com/data/icons/freeline/32/account_friend_human_man_member_person_profile_user_users-512.png" class="card-img" alt="user">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title"><%= product_owner(p).name %></h5>
                      <p class="card-text">Email: <%= product_owner(p).email %></p>
                      <p class="card-text"><small class="text-muted">Usuario registrado hace <%= time_ago_in_words(product_owner(p).created_at) %></small></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/products/new.html.erb
<h2 class="mt-4">Publicar aviso:</h2>
<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
<div class="form-group">
  <div class="form-row">
    <div class="col col-sm-6 col-md-3 my-2">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Ingrese su nombre...' %>
    </div>
    <div class="col col-sm-6 col-md-3 my-2">
      <%= f.text_field :email, class: 'form-control', placeholder: 'Ingrese su email...' %>
    </div>
    <div class="col col-sm-6 col-md-3 my-2">
      <%= f.password_field :password, class: 'form-control', placeholder: 'Ingrese su contraseña...' %>
    </div>
    <div class="col col-sm-6 col-md-3 my-2">
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirme su contraseña...' %>
    </div>
    <%= f.submit 'Ingresar', class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<h2 class="mt-5">Registro de nuevo usuario:</h2>

<%= render 'form' %>